version: '3'

services:
  database:
    container_name: Database
    # image: postgres
    build:
      context: database
      dockerfile: Dockerfile
    ports:
      - 5444:5432
    networks:
      - application-network
    volumes:
      - pg-data:/var/lib/postgresql/data

  backend:
    container_name: Backend
    build:
      context: backend
      dockerfile: Dockerfile
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/healtify
    ports:
      - 8080:8080
    networks:
      - application-network
    depends_on:
      - database


  frontend:
    container_name: Frontend
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - 80:3000
    depends_on:
      - backend
    stdin_open: true

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pg_admin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin_password
    ports:
      - "5050:80"
    networks:
      - application-network

networks:
  application-network:
    driver: bridge

volumes:
  pg-data: